// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: controlplane.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Client        string                 `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"` // "*" for wildcard
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *Target) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Target) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Target) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type Params struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LatencyMs      int32                  `protobuf:"varint,1,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	CorruptPct     int32                  `protobuf:"varint,3,opt,name=corrupt_pct,json=corruptPct,proto3" json:"corrupt_pct,omitempty"`
	PartialOkCount int32                  `protobuf:"varint,4,opt,name=partial_ok_count,json=partialOkCount,proto3" json:"partial_ok_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *Params) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *Params) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Params) GetCorruptPct() int32 {
	if x != nil {
		return x.CorruptPct
	}
	return 0
}

func (x *Params) GetPartialOkCount() int32 {
	if x != nil {
		return x.PartialOkCount
	}
	return 0
}

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Target        *Target                `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	FaultType     string                 `protobuf:"bytes,3,opt,name=fault_type,json=faultType,proto3" json:"fault_type,omitempty"` // "latency" | "error" | "corrupt_payload" | "drop_connection" | "partial_failure"
	Params        *Params                `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	Probability   float64                `protobuf:"fixed64,5,opt,name=probability,proto3" json:"probability,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	Version       int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,8,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"` // 0 = never expires
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Rule) GetFaultType() string {
	if x != nil {
		return x.FaultType
	}
	return ""
}

func (x *Rule) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Rule) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *Rule) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Rule) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Rule) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type CreateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *Rule                  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleRequest) Reset() {
	*x = CreateRuleRequest{}
	mi := &file_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleRequest) ProtoMessage() {}

func (x *CreateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRuleRequest) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type UpdateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *Rule                  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleRequest) Reset() {
	*x = UpdateRuleRequest{}
	mi := &file_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleRequest) ProtoMessage() {}

func (x *UpdateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRuleRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRuleRequest) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type DeleteRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleResponse) Reset() {
	*x = DeleteRuleResponse{}
	mi := &file_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleResponse) ProtoMessage() {}

func (x *DeleteRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRuleResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRuleResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GetRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleRequest) Reset() {
	*x = GetRuleRequest{}
	mi := &file_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleRequest) ProtoMessage() {}

func (x *GetRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleRequest.ProtoReflect.Descriptor instead.
func (*GetRuleRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *GetRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{8}
}

type ListRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *ListRulesResponse) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type SetActiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveRequest) Reset() {
	*x = SetActiveRequest{}
	mi := &file_controlplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveRequest) ProtoMessage() {}

func (x *SetActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveRequest.ProtoReflect.Descriptor instead.
func (*SetActiveRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{10}
}

func (x *SetActiveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetActiveRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type RuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *Rule                  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleResponse) Reset() {
	*x = RuleResponse{}
	mi := &file_controlplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleResponse) ProtoMessage() {}

func (x *RuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleResponse.ProtoReflect.Descriptor instead.
func (*RuleResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_rawDescGZIP(), []int{11}
}

func (x *RuleResponse) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

var File_controlplane_proto protoreflect.FileDescriptor

const file_controlplane_proto_rawDesc = "" +
	"\n" +
	"\x12controlplane.proto\x12\fcontrolplane\"R\n" +
	"\x06Target\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06client\x18\x03 \x01(\tR\x06client\"\x91\x01\n" +
	"\x06Params\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x01 \x01(\x05R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x1f\n" +
	"\vcorrupt_pct\x18\x03 \x01(\x05R\n" +
	"corruptPct\x12(\n" +
	"\x10partial_ok_count\x18\x04 \x01(\x05R\x0epartialOkCount\"\x8d\x02\n" +
	"\x04Rule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x06target\x18\x02 \x01(\v2\x14.controlplane.TargetR\x06target\x12\x1d\n" +
	"\n" +
	"fault_type\x18\x03 \x01(\tR\tfaultType\x12,\n" +
	"\x06params\x18\x04 \x01(\v2\x14.controlplane.ParamsR\x06params\x12 \n" +
	"\vprobability\x18\x05 \x01(\x01R\vprobability\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\x12&\n" +
	"\x0fexpires_at_unix\x18\b \x01(\x03R\rexpiresAtUnix\";\n" +
	"\x11CreateRuleRequest\x12&\n" +
	"\x04rule\x18\x01 \x01(\v2\x12.controlplane.RuleR\x04rule\";\n" +
	"\x11UpdateRuleRequest\x12&\n" +
	"\x04rule\x18\x01 \x01(\v2\x12.controlplane.RuleR\x04rule\"#\n" +
	"\x11DeleteRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteRuleResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\" \n" +
	"\x0eGetRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x12\n" +
	"\x10ListRulesRequest\"=\n" +
	"\x11ListRulesResponse\x12(\n" +
	"\x05rules\x18\x01 \x03(\v2\x12.controlplane.RuleR\x05rules\":\n" +
	"\x10SetActiveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\"6\n" +
	"\fRuleResponse\x12&\n" +
	"\x04rule\x18\x01 \x01(\v2\x12.controlplane.RuleR\x04rule2\xd1\x03\n" +
	"\fControlPlane\x12I\n" +
	"\n" +
	"CreateRule\x12\x1f.controlplane.CreateRuleRequest\x1a\x1a.controlplane.RuleResponse\x12I\n" +
	"\n" +
	"UpdateRule\x12\x1f.controlplane.UpdateRuleRequest\x1a\x1a.controlplane.RuleResponse\x12O\n" +
	"\n" +
	"DeleteRule\x12\x1f.controlplane.DeleteRuleRequest\x1a .controlplane.DeleteRuleResponse\x12C\n" +
	"\aGetRule\x12\x1c.controlplane.GetRuleRequest\x1a\x1a.controlplane.RuleResponse\x12L\n" +
	"\tListRules\x12\x1e.controlplane.ListRulesRequest\x1a\x1f.controlplane.ListRulesResponse\x12G\n" +
	"\tSetActive\x12\x1e.controlplane.SetActiveRequest\x1a\x1a.controlplane.RuleResponseB8Z6github.com/<yourusername>/faultline/controlplane/protob\x06proto3"

var (
	file_controlplane_proto_rawDescOnce sync.Once
	file_controlplane_proto_rawDescData []byte
)

func file_controlplane_proto_rawDescGZIP() []byte {
	file_controlplane_proto_rawDescOnce.Do(func() {
		file_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_proto_rawDesc), len(file_controlplane_proto_rawDesc)))
	})
	return file_controlplane_proto_rawDescData
}

var file_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_controlplane_proto_goTypes = []any{
	(*Target)(nil),             // 0: controlplane.Target
	(*Params)(nil),             // 1: controlplane.Params
	(*Rule)(nil),               // 2: controlplane.Rule
	(*CreateRuleRequest)(nil),  // 3: controlplane.CreateRuleRequest
	(*UpdateRuleRequest)(nil),  // 4: controlplane.UpdateRuleRequest
	(*DeleteRuleRequest)(nil),  // 5: controlplane.DeleteRuleRequest
	(*DeleteRuleResponse)(nil), // 6: controlplane.DeleteRuleResponse
	(*GetRuleRequest)(nil),     // 7: controlplane.GetRuleRequest
	(*ListRulesRequest)(nil),   // 8: controlplane.ListRulesRequest
	(*ListRulesResponse)(nil),  // 9: controlplane.ListRulesResponse
	(*SetActiveRequest)(nil),   // 10: controlplane.SetActiveRequest
	(*RuleResponse)(nil),       // 11: controlplane.RuleResponse
}
var file_controlplane_proto_depIdxs = []int32{
	0,  // 0: controlplane.Rule.target:type_name -> controlplane.Target
	1,  // 1: controlplane.Rule.params:type_name -> controlplane.Params
	2,  // 2: controlplane.CreateRuleRequest.rule:type_name -> controlplane.Rule
	2,  // 3: controlplane.UpdateRuleRequest.rule:type_name -> controlplane.Rule
	2,  // 4: controlplane.ListRulesResponse.rules:type_name -> controlplane.Rule
	2,  // 5: controlplane.RuleResponse.rule:type_name -> controlplane.Rule
	3,  // 6: controlplane.ControlPlane.CreateRule:input_type -> controlplane.CreateRuleRequest
	4,  // 7: controlplane.ControlPlane.UpdateRule:input_type -> controlplane.UpdateRuleRequest
	5,  // 8: controlplane.ControlPlane.DeleteRule:input_type -> controlplane.DeleteRuleRequest
	7,  // 9: controlplane.ControlPlane.GetRule:input_type -> controlplane.GetRuleRequest
	8,  // 10: controlplane.ControlPlane.ListRules:input_type -> controlplane.ListRulesRequest
	10, // 11: controlplane.ControlPlane.SetActive:input_type -> controlplane.SetActiveRequest
	11, // 12: controlplane.ControlPlane.CreateRule:output_type -> controlplane.RuleResponse
	11, // 13: controlplane.ControlPlane.UpdateRule:output_type -> controlplane.RuleResponse
	6,  // 14: controlplane.ControlPlane.DeleteRule:output_type -> controlplane.DeleteRuleResponse
	11, // 15: controlplane.ControlPlane.GetRule:output_type -> controlplane.RuleResponse
	9,  // 16: controlplane.ControlPlane.ListRules:output_type -> controlplane.ListRulesResponse
	11, // 17: controlplane.ControlPlane.SetActive:output_type -> controlplane.RuleResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_controlplane_proto_init() }
func file_controlplane_proto_init() {
	if File_controlplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_proto_rawDesc), len(file_controlplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_proto_goTypes,
		DependencyIndexes: file_controlplane_proto_depIdxs,
		MessageInfos:      file_controlplane_proto_msgTypes,
	}.Build()
	File_controlplane_proto = out.File
	file_controlplane_proto_goTypes = nil
	file_controlplane_proto_depIdxs = nil
}
