FROM golang:1.25-alpine AS build
RUN apk add --no-cache ca-certificates git
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /toyservice ./cmd/toyservice

FROM alpine:latest
RUN apk add --no-cache ca-certificates
COPY --from=build /toyservice /toyservice
EXPOSE 50051 9090
ENTRYPOINT ["/toyservice"]